### ISSUE TITLE
security.privileged=true

### ISSUE THREAD

**Issue by bengivre** [mr-io/lxd-consul#2]
Hi, 
thanks for sharing your work. 
Can you explain why are you using "security.privileged=true" for this configuration ?

Thanks

**Comment by mar-io** [comment]
The main reason is that I created rc scripts to daemonize consul. This requires the container to run with root privileges. That being said, this could theoretically be adjusted to create a resource user and run as that user. But since this is designed for testing and not production I went with the path of least resistance.

**Comment by bengivre** [comment]
It makes sense :) 
Thanks for your answer
